TechSupport/Controllers/ChannelsController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TechSupport;
using TechSupport.Models;
using TechSupport.signalr.hubs;

namespace TechSupport.Controllers
{
    public class ChannelsController : Controller
    {
        private TechSupport20190613121821_dbEntities db = new TechSupport20190613121821_dbEntities();

        // GET: Channels
        [Authorize(Roles = "user")]
        public ActionResult MyChannels()
        {
            var userId = User.Identity.GetUserId();
            var channels = db.Channels.Include(c => c.AspNetUser).Where(c => c.Creator == userId).Where(c => c.Closed == false);
            return View(channels.ToList());
        }

        [Authorize(Roles = "agent")]
        public ActionResult AllChannels()
        {
            var userId = User.Identity.GetUserId();
            var channels = db.Channels.Include(c => c.AspNetUser).Where(c => c.Closed == false);
            return View(channels.ToList());
        }

        [Authorize(Roles = "agent")]
        public ActionResult SignUp(int id)
        {
            Channel channel = db.Channels.Find(id);
            channel.AspNetUsers.Add(db.AspNetUsers.Find(User.Identity.GetUserId()));
            db.Entry(channel).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("AllChannels");
        }

        [Authorize(Roles = "agent")]
        public ActionResult SignOff(int id)
        {
            Channel channel = db.Channels.Find(id);
            channel.AspNetUsers.Remove(db.AspNetUsers.Find(User.Identity.GetUserId()));
            db.Entry(channel).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("AllChannels");
        }

        [Authorize]
        public ActionResult SendMessage(ChannelModel model, int channelId)
        {
            Message msg = new Message
            {
                Channel = channelId,
                Sender = User.Identity.GetUserId(),
                Text = model.message,
                TimeCreated = System.DateTime.Now
            };
            db.Messages.Add(msg);
            db.SaveChanges();

            ApplicationUserManager userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            string userId = User.Identity.GetUserId();
            List<string> roles = userManager.GetRoles(userId).ToList();

            MyHub.Send(User.Identity.GetUserName(), model.message, roles[0]);
            return RedirectToAction("Details", new { id = channelId});
        }

        //GET: Channels/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Channel c = db.Channels.Find(id);
            c.Messages = c.Messages.OrderByDescending(m => m.TimeCreated).ToList();
            if (c == null)
            {
                return HttpNotFound();
            }
            ChannelModel model = new ChannelModel
            {
                channel = c
            };
            return View(model);
        }

        // GET: Channels/Create
        [Authorize(Roles = "user")]
        public ActionResult Create()
        {
            ViewBag.Creator = new SelectList(db.AspNetUsers, "Id", "Email");
            return View();
        }

        // POST: Channels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "user")]
        public ActionResult Create([Bind(Include = "Id,Name,TimeCreated,Creator,Closed,Price")] Channel channel)
        {
            if (ModelState.IsValid)
            {
                AspNetUser user = db.AspNetUsers.Find(User.Identity.GetUserId());
                int channelPrice = db.ChannelPrices.First().NumTokens;

                if (user.Tokens < channelPrice)
                {
                    return View("NeedMoreGold");
                }
                else
                {
                    channel.Closed = false;
                    channel.Creator = user.Id;
                    channel.TimeCreated = DateTime.Now;
                    channel.Price = channelPrice;
                    db.Channels.Add(channel);

                    user.Tokens -= channelPrice;
                    db.Entry(user).State = EntityState.Modified;
                
                    db.SaveChanges();
                    return RedirectToAction("MyChannels");
                }
            }

            ViewBag.Creator = new SelectList(db.AspNetUsers, "Id", "Email", channel.Creator);
            return View(channel);
        }

        [Authorize(Roles = "user")]
        public ActionResult Close(int id)
        {
            Channel channel = db.Channels.Find(id);
            channel.Closed = true;
            db.Entry(channel).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("MyChannels");
        }

        // GET: Channels/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Channel channel = db.Channels.Find(id);
        //    if (channel == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.Creator = new SelectList(db.AspNetUsers, "Id", "Email", channel.Creator);
        //    return View(channel);
        //}

        //// POST: Channels/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,Name,TimeCreated,Creator,Closed,Price")] Channel channel)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(channel).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.Creator = new SelectList(db.AspNetUsers, "Id", "Email", channel.Creator);
        //    return View(channel);
        //}

        //// GET: Channels/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Channel channel = db.Channels.Find(id);
        //    if (channel == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(channel);
        //}

        //// POST: Channels/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Channel channel = db.Channels.Find(id);
        //    db.Channels.Remove(channel);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TechSupport/Controllers/TokenOrdersController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TechSupport;

namespace TechSupport.Controllers
{
    public class TokenOrdersController : Controller
    {
        private TechSupport20190613121821_dbEntities db = new TechSupport20190613121821_dbEntities();

        // GET: TokenOrders
        //public ActionResult Index()
        //{
        //    var tokenOrders = db.TokenOrders.Include(t => t.AspNetUser).Include(t => t.TokenPackage1);
        //    return View(tokenOrders.ToList());
        //}

        //// GET: TokenOrders/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    TokenOrder tokenOrder = db.TokenOrders.Find(id);
        //    if (tokenOrder == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(tokenOrder);
        //}

        [Authorize(Roles = "user")]
        public ActionResult MyOrders()
        {
            var userId = User.Identity.GetUserId();
            var tokenOrders = db.TokenOrders.Include(t => t.AspNetUser).Include(t => t.TokenPackage1).Where(t => t.Buyer == userId);
            return View(tokenOrders.ToList());
        }

        // GET: TokenOrders/Create
        [Authorize(Roles = "user")]
        public ActionResult Create()
        {
            ViewBag.Buyer = new SelectList(db.AspNetUsers, "Id", "Email");
            ViewBag.TokenPackage = new SelectList(db.TokenPackages, "Id", "Name");
            return View();
        }

        // POST: TokenOrders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "user")]
        public ActionResult Create([Bind(Include = "Id,TokenPackage")] TokenOrder tokenOrder)
        {
            if (ModelState.IsValid)
            {
                TokenPackage selectedPackage = db.TokenPackages.Find(tokenOrder.TokenPackage);
                AspNetUser buyer = db.AspNetUsers.Find(User.Identity.GetUserId());
                tokenOrder.Price = selectedPackage.Price;
                tokenOrder.NumTokens = selectedPackage.NumTokens;
                tokenOrder.Buyer = buyer.Id;
                db.TokenOrders.Add(tokenOrder);

                buyer.Tokens += selectedPackage.NumTokens;
                db.Entry(buyer).State = EntityState.Modified;

                db.SaveChanges();
                return RedirectToAction("MyOrders");
            }

            ViewBag.Buyer = new SelectList(db.AspNetUsers, "Id", "Email", tokenOrder.Buyer);
            ViewBag.TokenPackage = new SelectList(db.TokenPackages, "Id", "Name", tokenOrder.TokenPackage);
            return View(tokenOrder);
        }

        // GET: TokenOrders/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    TokenOrder tokenOrder = db.TokenOrders.Find(id);
        //    if (tokenOrder == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.Buyer = new SelectList(db.AspNetUsers, "Id", "Email", tokenOrder.Buyer);
        //    ViewBag.TokenPackage = new SelectList(db.TokenPackages, "Id", "Name", tokenOrder.TokenPackage);
        //    return View(tokenOrder);
        //}

        //// POST: TokenOrders/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,Buyer,NumTokens,Price,TokenPackage")] TokenOrder tokenOrder)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(tokenOrder).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.Buyer = new SelectList(db.AspNetUsers, "Id", "Email", tokenOrder.Buyer);
        //    ViewBag.TokenPackage = new SelectList(db.TokenPackages, "Id", "Name", tokenOrder.TokenPackage);
        //    return View(tokenOrder);
        //}

        //// GET: TokenOrders/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    TokenOrder tokenOrder = db.TokenOrders.Find(id);
        //    if (tokenOrder == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(tokenOrder);
        //}

        //// POST: TokenOrders/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    TokenOrder tokenOrder = db.TokenOrders.Find(id);
        //    db.TokenOrders.Remove(tokenOrder);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TechSupport/Views/Channels/AllChannels.cshtml
@using Microsoft.AspNet.Identity
@model IEnumerable<TechSupport.Channel>

@{
    ViewBag.Title = "All Channels";
    var UserId = User.Identity.GetUserId();
}

<h2>All Channels</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimeCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </th>
        <th>
            Agents
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @if (item.AspNetUsers.Where(u => u.Id == UserId).Any())
                {
                    @Html.ActionLink(item.Name, "Details", new { id = item.Id })
                }
                else
                {
                    @Html.DisplayFor(modelItem => item.Name)
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeCreated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AspNetUser.Email)
            </td>
            <td>
                @item.AspNetUsers.Count()
            </td>
            <td>
                @if (item.AspNetUsers.Where(u => u.Id == UserId).Any())
                {
                    @Html.ActionLink("SignOff", "SignOff", new { id = item.Id })
                }
                else
                {
                    @Html.ActionLink("SignUp", "SignUp", new { id = item.Id })
                }
            </td>
        </tr>
    }

</table>

TechSupport/Views/Channels/Create.cshtml
@model TechSupport.Channel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Channel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.TimeCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimeCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Creator, "Creator", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Creator", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Creator, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Closed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Closed)
                    @Html.ValidationMessageFor(model => model.Closed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TechSupport/Views/Channels/Delete.cshtml
@model TechSupport.Channel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Channel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Closed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Closed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TechSupport/Views/Channels/Details.cshtml
@using Microsoft.AspNet.Identity;
@using TechSupport.Models;
@using Microsoft.AspNet.Identity.EntityFramework;
@model TechSupport.Models.ChannelModel

@{
    ViewBag.Title = "Details";
    ApplicationDbContext userscontext = new ApplicationDbContext();
    var userStore = new UserStore<ApplicationUser>(userscontext);
    var userManager = new UserManager<ApplicationUser>(userStore);
}

<style type="text/css">
    .chatBoxLeft {
        width: 300px;
        margin: 20px;
        margin-left: 0;
        margin-right: auto;
        background: #00bfb6;
        padding: 20px;
        text-align: left;
        font-weight: 900;
        color: #fff;
        font-family: arial;
        position:relative;
    }

    .chatBoxRight {
        width: 300px;
        margin: 20px;
        margin-left: auto;
        margin-right: 0;
        border: 4px solid #00bfb6;
        padding: 20px;
        text-align: right;
        font-weight: 900;
        color: #00bfb6;
        font-family: arial;
        position: relative;
    }

    .chatBoxLeft:before {
        content: "";
        width: 0px;
        height: 0px;
        position: absolute;
        border-left: 10px solid #00bfb6;
        border-right: 10px solid transparent;
        border-top: 10px solid #00bfb6;
        border-bottom: 10px solid transparent;
        right: -20px;
        top: 6px;
    }

    .chatBoxRight:before {
        content: "";
        width: 0px;
        height: 0px;
        position: absolute;
        border-left: 10px solid transparent;
        border-right: 10px solid #00bfb6;
        border-top: 10px solid #00bfb6;
        border-bottom: 10px solid transparent;
        left: -21px;
        top: 6px;
    }

    .chatBoxRight:after {
        content: "";
        width: 0px;
        height: 0px;
        position: absolute;
        border-left: 7px solid transparent;
        border-right: 7px solid #fff;
        border-top: 7px solid #fff;
        border-bottom: 7px solid transparent;
        left: -11px;
        top: 10px;
    }
</style>

<h2>Details</h2>

<div>
    <h4>Channel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.channel.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.channel.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.channel.TimeCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.channel.TimeCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.channel.Closed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.channel.Closed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.channel.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.channel.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.channel.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.channel.AspNetUser.Email)
        </dd>

    </dl>
</div>

<p>
    @Html.ActionLink("Back to List", "Index")
</p>
<hr />


@using (Html.BeginForm("SendMessage", "Channels", new { channelId = Model.channel.Id }, FormMethod.Post, null))
{
    <div class="form-horizontal">
        <div class="form-inline">
            <div class="form-group">
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.message, new { @class = "form-control", autocomplete = "off", placeholder = "Text" })
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Send" class="btn btn-primary btn-sm" />
            </div>
        </div>
    </div>
}

<div id="discussion">
    @foreach (var item in Model.channel.Messages)
    {
        if (!userManager.IsInRole(item.Sender, "user"))
        {
            <div class="chatBoxLeft">
                <strong>@item.AspNetUser.UserName</strong>
                <br />
                @item.Text
            </div>
        }
        else
        {
            <div class="chatBoxRight">
                <strong>@item.AspNetUser.UserName</strong>
                <br />
                @item.Text
            </div>
        }
    }
</div>


@section scripts {
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.signalR-2.4.1.min.js"></script>
    <script src="~/signalr/hubs/"></script>
    <script type="text/javascript">
        $(function () {

            //var userscontext = new ApplicationDbContext();
            //var userStore = new UserStore<ApplicationUser>(userscontext);
            //var userManager = new UserManager<ApplicationUser>(userStore);

            var chat = $.connection.myHub;
            chat.client.addNewMessage = function (name, message, role) {
                if (role == 'user') {
                    $('#discussion').prepend(
                        '<div class="chatBoxRight">' +
                        '<strong>' +
                        name +
                        '</strong><br />' +
                        message +
                        '</div>');
                } else {
                    $('#discussion').prepend(
                        '<div class="chatBoxLeft">' +
                        '<strong>' +
                        name +
                        '</strong><br />' +
                        message +
                        '</div>');
                }

                //$('#discussion').append('<li><strong>' + htmlEncode(name) + '</strong>: ' + htmlEncode(message) + '</li>');
                $('#message').focus();
            }

            $.connection.hub.start().done(function () {
                //console.log('started');
                //$('#sendMessage').click(function () {
                //    var username = $('#logoutForm').find('a').html();
                //    username = username.substring(6, username.length - 1);
                //    console.log(username);
                //    chat.server.send(username, $('#message').val());
                //    $('#message').val('');
                //});
            });
        });

        //function htmlEncode(value) {
        //    var encodedValue = $('<div />').text(value).html();
        //    return encodedValue;
        //}
    </script>
}

TechSupport/Views/Channels/Edit.cshtml
@model TechSupport.Channel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Channel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimeCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Creator, "Creator", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Creator", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Creator, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Closed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Closed)
                    @Html.ValidationMessageFor(model => model.Closed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TechSupport/Views/Channels/NeedMoreGold.cshtml
@{
    ViewBag.Title = "NeedMoreGold";
}

<hgroup>
    <h1 class="text-danger">Insufficient number of tokens</h1>
    @Html.ActionLink("Buy Tokens", "Create", "TokenOrders", null, null)
</hgroup>