TechSupport/Controllers/AnswersController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TechSupport;

namespace TechSupport.Controllers
{
    public class AnswersController : Controller
    {
        private TechSupport20190613121821_dbEntities db = new TechSupport20190613121821_dbEntities();

        // GET: Answers
        public ActionResult Index()
        {
            var answers = db.Answers.Include(a => a.Answer1).Include(a => a.AspNetUser).Include(a => a.Question1);
            return View(answers.ToList());
        }

        // GET: Answers/Details/5
        public ActionResult Details(int? id, string sort)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = 
                db.Answers
                .Include(a => a.Answers1.Select(a1 => a1.AspNetUser))
                .SingleOrDefault(a => a.Id == id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            if (sort != null)
            {
                string sortOrder = (string)TempData["sortOrder"];
                if (sortOrder != null && sortOrder.Contains(sort) && sortOrder.Contains("desc"))
                {
                    sortOrder = sort + "_" + "asc";
                }
                else
                {
                    sortOrder = sort + "_" + "desc";
                }
                TempData["sortOrder"] = sortOrder;

            }

            return View(answer);
        }

        public Answer SortAnswers(Answer answer, string sortOrder)
        {
            switch (sortOrder)
            {
                case "time_asc":
                    answer.Answers1 = answer.Answers1.OrderBy(a => a.TimeCreated).ToList();
                    break;
                case "time_desc":
                    answer.Answers1 = answer.Answers1.OrderByDescending(a => a.TimeCreated).ToList();
                    break;
                case "likes_asc":
                    answer.Answers1 = answer.Answers1.OrderBy(a => a.Ratings.Where(r => r.Likes.Equals(true)).Count()).ToList();
                    break;
                case "likes_desc":
                    answer.Answers1 = answer.Answers1.OrderByDescending(a => a.Ratings.Where(r => r.Likes.Equals(true)).Count()).ToList();
                    break;
                case "dislikes_asc":
                    answer.Answers1 = answer.Answers1.OrderBy(a => a.Ratings.Where(r => r.Likes.Equals(false)).Count()).ToList();
                    break;
                case "dislikes_desc":
                    answer.Answers1 = answer.Answers1.OrderByDescending(a => a.Ratings.Where(r => r.Likes.Equals(false)).Count()).ToList();
                    break;
            }
            return answer;
        }

        // GET: Answers/Create
        public ActionResult Create(int? QuestionId, int? ReplyOn)
        {
            ViewBag.ReplyOn = new SelectList(db.Answers, "Id", "Author");
            ViewBag.Author = new SelectList(db.AspNetUsers, "Id", "Email");
            ViewBag.Question = new SelectList(db.Questions, "Id", "Title");
            TempData["QuestionToAnswer"] = QuestionId;
            TempData["AnswerToReply"] = ReplyOn;
            return View();
        }

        // POST: Answers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Text")] Answer answer)
        {
            int? QuestionId = (int?)TempData["QuestionToAnswer"];
            int? ReplyOn = (int?)TempData["AnswerToReply"];
            if (ModelState.IsValid)
            {
                answer.TimeCreated = DateTime.Now;
                answer.Question = QuestionId;
                answer.Author = User.Identity.GetUserId();
                answer.ReplyOn = ReplyOn;
                db.Answers.Add(answer);
                db.SaveChanges();
                return RedirectToAction("Index", "Questions");
            }

            ViewBag.ReplyOn = new SelectList(db.Answers, "Id", "Author", answer.ReplyOn);
            ViewBag.Author = new SelectList(db.AspNetUsers, "Id", "Email", answer.Author);
            ViewBag.Question = new SelectList(db.Questions, "Id", "Title", answer.Question);
            return View(answer);
        }

        // GET: Answers/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Answer answer = db.Answers.Find(id);
        //    if (answer == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.ReplyOn = new SelectList(db.Answers, "Id", "Author", answer.ReplyOn);
        //    ViewBag.Author = new SelectList(db.AspNetUsers, "Id", "Email", answer.Author);
        //    ViewBag.Question = new SelectList(db.Questions, "Id", "Title", answer.Question);
        //    return View(answer);
        //}

        //// POST: Answers/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,Question,ReplyOn,Author,TimeCreated,Text")] Answer answer)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(answer).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.ReplyOn = new SelectList(db.Answers, "Id", "Author", answer.ReplyOn);
        //    ViewBag.Author = new SelectList(db.AspNetUsers, "Id", "Email", answer.Author);
        //    ViewBag.Question = new SelectList(db.Questions, "Id", "Title", answer.Question);
        //    return View(answer);
        //}

        // GET: Answers/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Answer answer = db.Answers.Find(id);
        //    if (answer == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(answer);
        //}

        //// POST: Answers/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Answer answer = db.Answers.Include(a => a.Answers1).SingleOrDefault(a => a.Id.Equals(id));
        //    DeleteAnswer(answer);
        //    return RedirectToAction("Index");
        //}

        [Authorize(Roles = "admin")]
        public ActionResult Delete(int AnswerId, int QuestionId)
        {
            Answer answer = db.Answers.Include(a => a.Answers1).SingleOrDefault(a => a.Id.Equals(AnswerId));
            DeleteAnswer(answer);
            return Redirect("/Questions/Details/" + QuestionId);
        }

        [Authorize(Roles = "admin")]
        public ActionResult Delete(int AnswerId)
        {
            Answer answer = db.Answers.Include(a => a.Answers1).SingleOrDefault(a => a.Id.Equals(AnswerId));
            DeleteAnswer(answer);
            return Redirect("/Answers/Details/" + AnswerId);
        }

        public void DeleteAnswer(Answer answer)
        {
            if (answer.Answers1 != null)
            {
                foreach (var a in answer.Answers1.ToList())
                {
                    Answer ans = db.Answers.Include(an => an.Answers1).SingleOrDefault(an => an.Id.Equals(a.Id));
                    DeleteAnswer(ans);
                }
            } 
            db.Answers.Remove(answer);
            db.SaveChanges();            
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TechSupport/Controllers/AspNetUsersController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TechSupport;

namespace TechSupport.Controllers
{
    public class AspNetUsersController : Controller
    {
        private TechSupport20190613121821_dbEntities db = new TechSupport20190613121821_dbEntities();

        // GET: AspNetUsers
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            List<AspNetUser> users = db.AspNetUsers.ToList();
            AspNetUser adminUser = db.AspNetUsers.FirstOrDefault(user => user.Email == "admin@admin.com");
            users.Remove(adminUser);
            return View(users);
        }

        // GET: AspNetUsers/Details/5
        //public ActionResult Details(string id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    AspNetUser aspNetUser = db.AspNetUsers.Find(id);
        //    if (aspNetUser == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(aspNetUser);
        //}

        // GET: AspNetUsers/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: AspNetUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async System.Threading.Tasks.Task<ActionResult> Create([Bind(Include = "Email,UserName,FirstName,LastName")] AspNetUser aspNetUser)
        {
            if (ModelState.IsValid)
            {
                db.AspNetUsers.Add(aspNetUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aspNetUser);
        }

        // GET: AspNetUsers/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // POST: AspNetUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit([Bind(Include = "Id,Email,UserName,FirstName,LastName")] AspNetUser aspNetUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aspNetUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aspNetUser);
        }


        [Authorize(Roles = "admin")]
        public ActionResult Disable(string id)
        {
            var aspNetUser = db.AspNetUsers.Find(id);
            aspNetUser.LockoutEnabled = true;
            aspNetUser.LockoutEndDateUtc = DateTime.Now;    
            db.Entry(aspNetUser).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "admin")]
        public ActionResult Enable(string id)
        {
            var aspNetUser = db.AspNetUsers.Find(id);
            aspNetUser.LockoutEnabled = false;
            db.Entry(aspNetUser).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        // GET: AspNetUsers/Delete/5
        //public ActionResult Delete(string id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    AspNetUser aspNetUser = db.AspNetUsers.Find(id);
        //    if (aspNetUser == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(aspNetUser);
        //}

        //// POST: AspNetUsers/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(string id)
        //{
        //    AspNetUser aspNetUser = db.AspNetUsers.Find(id);
        //    db.AspNetUsers.Remove(aspNetUser);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TechSupport/Controllers/ChannelPricesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TechSupport;

namespace TechSupport.Controllers
{
    public class ChannelPricesController : Controller
    {
        private TechSupport20190613121821_dbEntities db = new TechSupport20190613121821_dbEntities();

        // GET: ChannelPrices
        //public ActionResult Index()
        //{
        //    return View(db.ChannelPrices.ToList());
        //}

        //// GET: ChannelPrices/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    ChannelPrice channelPrice = db.ChannelPrices.Find(id);
        //    if (channelPrice == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(channelPrice);
        //}

        //// GET: ChannelPrices/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: ChannelPrices/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,NumTokens")] ChannelPrice channelPrice)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.ChannelPrices.Add(channelPrice);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(channelPrice);
        //}

        // GET: ChannelPrices/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit()
        {
            ChannelPrice channelPrice = db.ChannelPrices.First();
            if (channelPrice == null)
            {
                return HttpNotFound();
            }
            return View(channelPrice);
        }

        // POST: ChannelPrices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit([Bind(Include = "Id,NumTokens")] ChannelPrice channelPrice)
        {
            if (ModelState.IsValid)
            {
                db.Entry(channelPrice).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home", null);
            }
            return View(channelPrice);
        }

        // GET: ChannelPrices/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    ChannelPrice channelPrice = db.ChannelPrices.Find(id);
        //    if (channelPrice == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(channelPrice);
        //}

        //// POST: ChannelPrices/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    ChannelPrice channelPrice = db.ChannelPrices.Find(id);
        //    db.ChannelPrices.Remove(channelPrice);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TechSupport/Views/Shared/AnswerModal.cshtml
@model TechSupport.Models.AnswerQuestionViewModel


<div class="modal-header">
    <h5 class="modal-title">Add your bid</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
@using (Html.BeginForm("ReplyAnswer", "Answers", Model, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-body">
        <div class="form-horizontal">
            <div class="form-group">
                @Html.TextBoxFor(model => model.AnswerText)
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
    </div>
}

TechSupport/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript">
        var appInsights=window.appInsights||function(config){
            function r(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},u=document,e=window,o="script",s=u.createElement(o),i,f;for(s.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace","Ajax"];i.length;)r("track"+i.pop());return r("setAuthenticatedUserContext"),r("clearAuthenticatedUserContext"),config.disableExceptionTracking||(i="onerror",r("_"+i),f=e[i],e[i]=function(config,r,u,e,o){var s=f&&f(config,r,u,e,o);return s!==!0&&t["_"+i](config,r,u,e,o),s}),t
        }({
            instrumentationKey:"d452fc00-5b35-42a8-94fe-253e29fea381"
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Technical Support", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Questions", "Index", "Questions", new { page = 1 }, null)</li>
                    <li>@Html.ActionLink("Search", "Search", "Questions")</li>
                    @if (Request.IsAuthenticated)
                    {
                        if (User.IsInRole("user"))
                        {
                            <li>@Html.ActionLink("Channels", "MyChannels", "Channels")</li>
                            <li>@Html.ActionLink("Buy Tokens", "Create", "TokenOrders")</li>
                            <li>@Html.ActionLink("My Orders", "MyOrders", "TokenOrders")</li>
                        }
                        if (User.IsInRole("admin"))
                        {
                            <li>@Html.ActionLink("Categories", "Index", "Categories")</li>
                            <li>@Html.ActionLink("Users", "Index", "AspNetUsers")</li>
                            <li>@Html.ActionLink("Create Agent", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                            <li>@Html.ActionLink("Channel Price", "Edit", "ChannelPrices")</li>
                            <li>@Html.ActionLink("Packages", "Index", "TokenPackages")</li>
                        }
                        if (User.IsInRole("agent"))
                        {
                            <li>@Html.ActionLink("Channels", "AllChannels", "Channels")</li>
                        }
                    }                    
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>