TechSupport/Controllers/QuestionsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TechSupport;
using TechSupport.Models;
using PagedList;

namespace TechSupport.Controllers
{
    public class QuestionsController : Controller
    {
        private TechSupport20190613121821_dbEntities db = new TechSupport20190613121821_dbEntities();

        // GET: Questions
        public ActionResult Index(int page = 1)
        {
            ViewBag.Category = new SelectList(db.Categories, "Id", "Name");
            var questions = db.Questions.Include(q => q.Channel1).Include(q => q.Category1);
            List<QuestionsIndexViewModelItem> questionList = new List<QuestionsIndexViewModelItem>();
            foreach (var question in questions)
            {
                var user = db.AspNetUsers.FirstOrDefault(usr => question.Author == usr.Id);
                QuestionsIndexViewModelItem modelItem = new QuestionsIndexViewModelItem()
                {
                    Question = question,
                    AuthorName = user.FirstName + " " + user.LastName,
                    AnswerCount = question.Answers.Count()
                };
                questionList.Add(modelItem);
            }
            QuestionsIndexViewModel model = new QuestionsIndexViewModel();
            model.Questions = questionList.ToPagedList(page,10);
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(QuestionsIndexViewModel model)
        {
            ViewBag.Category = new SelectList(db.Categories, "Id", "Name");
            var questions = db.Questions.Include(q => q.Channel1).Include(q => q.Category1).Where(question => question.Category == model.Category);
            List<QuestionsIndexViewModelItem> questionList = new List<QuestionsIndexViewModelItem>();
            foreach (var question in questions)
            {
                var user = db.AspNetUsers.FirstOrDefault(usr => question.Author == usr.Id);
                QuestionsIndexViewModelItem modelItem = new QuestionsIndexViewModelItem()
                {
                    Question = question,
                    AuthorName = user.FirstName + " " + user.LastName,
                    AnswerCount = question.Answers.Count()
                };
                questionList.Add(modelItem);
            }
            QuestionsIndexViewModel newModel = new QuestionsIndexViewModel();
            newModel.Questions = questionList.ToPagedList(1, 10);
            return View(newModel);
        }

        public ActionResult Rate(string UserId, int AnswerId, bool Likes)
        {
            Rating rating = new Rating
            {
                AspNetUser = UserId,
                Answer = AnswerId,
                Likes = Likes
            };
            db.Ratings.Add(rating);
            db.SaveChanges();
            return View();
        }

        [Authorize(Roles = "user")]
        public ActionResult MyQuestions()
        {
            var userId = User.Identity.GetUserId();
            var questions = db.Questions.Include(q => q.Channel1).Include(q => q.Category1).Where(question => question.Author == userId);
            var user = db.AspNetUsers.FirstOrDefault(usr => userId == usr.Id);
            List<QuestionsIndexViewModelItem> questionList = new List<QuestionsIndexViewModelItem>();
            foreach (var question in questions)
            {
                QuestionsIndexViewModelItem modelItem = new QuestionsIndexViewModelItem()
                {
                    Question = question,
                    AuthorName = user.FirstName + " " + user.LastName,
                    AnswerCount = question.Answers.Count()
                };
                questionList.Add(modelItem);
            }
            return View(questionList);
        }

        public ActionResult Search()
        {
            QuestionsSearchViewModel model = new QuestionsSearchViewModel();
            model.Questions = new List<QuestionsIndexViewModelItem>();
            return View(model);
        }

        [HttpPost]
        public ActionResult Search(QuestionsSearchViewModel model)
        {
            var questions = db.Questions.Include(q => q.Channel1).Include(q => q.Category1).Where(question => question.Title.Contains(model.SearchString));
            List<QuestionsIndexViewModelItem> questionList = new List<QuestionsIndexViewModelItem>();
            
            foreach (var question in questions)
            {
                var user = db.AspNetUsers.FirstOrDefault(usr => question.Author == usr.Id);
                QuestionsIndexViewModelItem modelItem = new QuestionsIndexViewModelItem()
                {
                    Question = question,
                    AuthorName = user.FirstName + " " + user.LastName,
                    AnswerCount = question.Answers.Count()
                };
               questionList.Add(modelItem);
            }
            QuestionsSearchViewModel newModel = new QuestionsSearchViewModel();
            newModel.Questions = questionList;
            return View(newModel);
        }

        // GET: Questions/Details/5
        public ActionResult Details(int? id, string sort)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = 
                db.Questions
                .Include(q => q.Answers.Select(a => a.AspNetUser))
                .SingleOrDefault(q => q.Id == id);
            if (question == null)
            {
                return HttpNotFound();
            }
            if (sort != null)
            {
                string sortOrder = (string)TempData["sortOrder"];
                if (sortOrder != null && sortOrder.Contains(sort) && sortOrder.Contains("desc"))
                {
                    sortOrder = sort + "_" + "asc";
                } else
                {
                    sortOrder = sort + "_" + "desc";
                }
                TempData["sortOrder"] = sortOrder;
                question = SortAnswers(question, sortOrder);
            }

            return View(question);
        }

        public Question SortAnswers(Question question, string sortOrder)
        {
            switch (sortOrder)
            {
                case "time_asc":
                    question.Answers = question.Answers.OrderBy(a => a.TimeCreated).ToList();
                    break;
                case "time_desc":
                    question.Answers = question.Answers.OrderByDescending(a => a.TimeCreated).ToList();
                    break;
                case "likes_asc":
                    question.Answers = question.Answers.OrderBy(a => a.Ratings.Where(r => r.Likes.Equals(true)).Count()).ToList();
                    break;
                case "likes_desc":
                    question.Answers = question.Answers.OrderByDescending(a => a.Ratings.Where(r => r.Likes.Equals(true)).Count()).ToList();
                    break;
                case "dislikes_asc":
                    question.Answers = question.Answers.OrderBy(a => a.Ratings.Where(r => r.Likes.Equals(false)).Count()).ToList();
                    break;
                case "dislikes_desc":
                    question.Answers = question.Answers.OrderByDescending(a => a.Ratings.Where(r => r.Likes.Equals(false)).Count()).ToList();
                    break;
            }
            return question;
        }

        // GET: Questions/Create
        [Authorize(Roles = "user")]
        public ActionResult Create()
        {
            ViewBag.Channel = new SelectList(db.Channels, "Id", "Name");
            ViewBag.Category = new SelectList(db.Categories, "Id", "Name");
            return View();
        }

        // POST: Questions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "user")]
        public ActionResult Create([Bind(Include = "Id,Title,Text,Image,Category,Author,TimeCreated,TimeLastLocked,LockoutEnabled,Channel,Locked")] Question question)
        {
            if (ModelState.IsValid)
            {
                question.Author = User.Identity.GetUserId();
                question.TimeCreated = DateTime.Now;
                question.Locked = false;
                question.LockoutEnabled = true;

                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Channel = new SelectList(db.Channels, "Id", "Name", question.Channel);
            ViewBag.Category = new SelectList(db.Categories, "Id", "Name", question.Category);
            return View(question);
        }

        // GET: Questions/Delete/5
        [Authorize(Roles = "user, admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Questions/Delete/5
        [Authorize(Roles = "user, admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            db.Questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {

TechSupport/Controllers/RatingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TechSupport;

namespace TechSupport.Controllers
{
    public class RatingsController : Controller
    {
        private TechSupport20190613121821_dbEntities db = new TechSupport20190613121821_dbEntities();

        // GET: Ratings
        public ActionResult Index()
        {
            var ratings = db.Ratings.Include(r => r.Answer1).Include(r => r.AspNetUser1);
            return View(ratings.ToList());
        }

        // GET: Ratings/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rating rating = db.Ratings.Find(id);
            if (rating == null)
            {
                return HttpNotFound();
            }
            return View(rating);
        }

        // GET: Ratings/Create
        //public ActionResult Create()
        //{
        //    ViewBag.Answer = new SelectList(db.Answers, "Id", "Author");
        //    ViewBag.AspNetUser = new SelectList(db.AspNetUsers, "Id", "Email");
        //    return View();
        //}

        // POST: Ratings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "AspNetUser,Answer,Likes")] Rating rating)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Ratings.Add(rating);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.Answer = new SelectList(db.Answers, "Id", "Author", rating.Answer);
        //    ViewBag.AspNetUser = new SelectList(db.AspNetUsers, "Id", "Email", rating.AspNetUser);
        //    return View(rating);
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult CreateForQuestions(string UserId, int AnswerId, bool Likes, int QuestionId)
        {
            Rating Rating = db.Ratings.Find(UserId, AnswerId);
            if (Rating != null)
            {
                Rating.Likes = Likes;
                db.Entry(Rating).State = EntityState.Modified;
            }
            else
            {
                Rating = new Rating
                {
                    AspNetUser = UserId,
                    Answer = AnswerId,
                    Likes = Likes
                };
                db.Ratings.Add(Rating);
            }
            db.SaveChanges();
            return Redirect("/Questions/Details/" + QuestionId);
        }

        [Authorize]
        public ActionResult CreateForAnswer(string UserId, int AnswerId, bool Likes, int QuestionId)
        {
            Rating Rating = db.Ratings.Find(UserId, AnswerId);
            if (Rating != null)
            {
                Rating.Likes = Likes;
                db.Entry(Rating).State = EntityState.Modified;
            }
            else
            {
                Rating = new Rating
                {
                    AspNetUser = UserId,
                    Answer = AnswerId,
                    Likes = Likes
                };
                db.Ratings.Add(Rating);
            }
            db.SaveChanges();
            return Redirect("/Answers/Details/" + QuestionId);
        }

        // GET: Ratings/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rating rating = db.Ratings.Find(id);
            if (rating == null)
            {
                return HttpNotFound();
            }
            ViewBag.Answer = new SelectList(db.Answers, "Id", "Author", rating.Answer);
            ViewBag.AspNetUser = new SelectList(db.AspNetUsers, "Id", "Email", rating.AspNetUser);
            return View(rating);
        }

        // POST: Ratings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AspNetUser,Answer,Likes")] Rating rating)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rating).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Answer = new SelectList(db.Answers, "Id", "Author", rating.Answer);
            ViewBag.AspNetUser = new SelectList(db.AspNetUsers, "Id", "Email", rating.AspNetUser);
            return View(rating);
        }

        // GET: Ratings/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rating rating = db.Ratings.Find(id);
            if (rating == null)
            {
                return HttpNotFound();
            }
            return View(rating);
        }

        // POST: Ratings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Rating rating = db.Ratings.Find(id);
            db.Ratings.Remove(rating);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //public ActionResult Delete(int AnswerId, int QuestionId)
        //{
        //    Rating rating = db.Ratings.Find(AnswerId);
        //    db.Ratings.Remove(rating);
        //    db.SaveChanges();
        //    return Redirect("/Questions/Details/" + QuestionId);
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TechSupport/Views/Questions/Delete.cshtml
@model TechSupport.Question

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeLastLocked)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeLastLocked)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Locked)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Locked)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Channel1.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Channel1.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category1.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category1.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TechSupport/Views/Questions/Details.cshtml
@using Microsoft.AspNet.Identity
@model TechSupport.Question

@{
    ViewBag.Title = "Details";
}

<h2>Question Details</h2>

<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Locked)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Locked)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Channel1.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Channel1.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category1.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category1.Name)
        </dd>
    </dl>
</div>

<hr />

<h2>Answers</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Text)
        </th >
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        <th>
            @Html.ActionLink("TimeCreated", "Details", new { id = Model.Id, sort = "time" })
        </th>
        <th>
            @Html.ActionLink("Likes", "Details", new { id = Model.Id, sort = "likes" })
        </th>
        <th>
            @Html.ActionLink("Dislikes", "Details", new { id = Model.Id, sort = "dislikes" })
        </th>
    </tr>
    @foreach (var item in Model.Answers)
    {
        <tr>
            <td>
                @Html.ActionLink(item.Text, "Details", "Answers", new { id = item.Id }, null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AspNetUser.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeCreated)
            </td>
            <td>
                @{ 
                    int likes = item.Ratings.Where(r => r.Likes.Equals(true)).Count();
                }
                @if (Request.IsAuthenticated)
                {
                    @Html.ActionLink("Like ", "CreateForQuestions", "Ratings", new { UserId = User.Identity.GetUserId(), AnswerId = item.Id, Likes = true, QuestionId = Model.Id }, null);
                }
                @Html.DisplayFor(modelItem => likes)
            </td>
            <td>
                @{
                    int dislikes = item.Ratings.Where(r => r.Likes.Equals(false)).Count();
                }
                @if (Request.IsAuthenticated)
                {
                    @Html.ActionLink("Dislike ", "CreateForQuestions", "Ratings", new { UserId = User.Identity.GetUserId(), AnswerId = item.Id, Likes = false, QuestionId = Model.Id }, null)
                }
                @Html.DisplayFor(modelItem => dislikes)
            </td>
            <td>
                @Html.ActionLink("Answer ", "Create", "Answers", new { ReplyOn = item.Id }, null)
                @if (User.IsInRole("admin"))
                {
                    @Html.ActionLink("Delete ", "Delete", "Answers", new { AnswerId = item.Id, QuestionId = Model.Id }, null)
                }
            </td>
        </tr>
}
</table>

@*<div id="MyModal" class="modal fade" tabindex="-1" role="dialog" style="border: 5px solid #3A87AD;">
    <div class="modal-dialog">
        @using (Html.BeginForm("Search", "Questions", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            <div class="modal-content" style="width:500px !important; margin: 10px auto !important;">
                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="form-group">
                            @Html.LabelFor(model => model.BidAmount, htmlAttributes: new { @class = "col-form-label" })
                            @Html.TextBoxFor(model => model.BidAmount, new { @Value = 1 })
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-primary" data-dismiss="modal">Submit</button>
                    <button class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
            </div>
        }
    </div>
</div>*@

<p>
    @Html.ActionLink("Back to List", "Index")
</p>

TechSupport/Views/Questions/Index.cshtml
@using Microsoft.AspNet.Identity
@using PagedList.Mvc
@model TechSupport.Models.QuestionsIndexViewModel

@{
    ViewBag.Title = "Index";
}

<style type="text/css">
    .true {
        background-color: coral;
        opacity : 0.8;
        color : white;
    }
    .false {
        background-color: white;
    }
    .true td a {
        color : white;
        text-decoration : none;
    }
    .true td a:hover {
        color : crimson;
    }
</style>

<h2>Index</h2>

@using (Html.BeginForm("Index", "Questions", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <div class="form-horizontal">
        <div class="form-inline">
            <div class="form-group">
                @Html.LabelFor(m => m.Category, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.DropDownList("Category", null, htmlAttributes: new { @class = "col-md-offset-4 form-control" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-8 col-md-10">
                    <input type="submit" value="Search" class="btn btn-primary btn-sm" />
                </div>
            </div>
        </div>
    </div>
}

<hr />

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<p>
    @Html.ActionLink("My Questions", "MyQuestions")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Questions.First().Question.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Questions.First().AuthorName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Questions.First().AnswerCount)
        </th>
        <th>
            Action
        </th>
    </tr>

    @foreach (var item in Model.Questions)
    {
        <tr class="@item.Question.Locked.ToString().ToLower()">
            <td>
                @Html.ActionLink(item.Question.Title, "Details", new { id = item.Question.Id, sort = "time" })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AuthorName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AnswerCount)
            </td>
            <td class="action">
                @*@Html.ActionLink("Details  ", "Details", new { id = item.Question.Id })*@
                @if (User.Identity.GetUserId() == item.Question.Author)
                {
                    if (!item.Question.Locked)
                    {
                        @Html.ActionLink("Close  ", "Close", new { id = item.Question.Id });
                    }
                    @Html.ActionLink("Delete  ", "Delete", new { id = item.Question.Id })
                }
                @if (User.IsInRole("admin"))
                {
                    if (item.Question.Locked)
                    {
                        @Html.ActionLink("Open  ", "Open", new { id = item.Question.Id });
                    }
                    @Html.ActionLink("Delete  ", "Delete", new { id = item.Question.Id })
                }
                @if (User.IsInRole("agent"))
                {
                    if (item.Question.Locked)
                    {
                        @Html.ActionLink("Open  ", "Open", new { id = item.Question.Id });
                    }
                }
                @if (User.Identity.IsAuthenticated)
                {
                    if (!item.Question.Locked)
                    {
                        @Html.ActionLink("Answer  ", "Create", "Answers", new { QuestionId = item.Question.Id }, null);
                    }
                }
            </td>
        </tr>
    }
</table>

Page @(Model.Questions.PageCount < Model.Questions.PageNumber ? 0 : Model.Questions.PageNumber) of @Model.Questions.PageCount
@Html.PagedListPager(Model.Questions, page => Url.Action("Index", new { page }))

TechSupport/Views/Questions/Search.cshtml
@using Microsoft.AspNet.Identity
@model TechSupport.Models.QuestionsSearchViewModel

@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>

@using (Html.BeginForm("Search", "Questions", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(m => m.SearchString, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.SearchString, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-8 col-md-10">
                <input type="submit" value="Search" class="btn btn-primary btn-sm" />
            </div>
        </div>
    </div>
}


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Questions.First().Question.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Questions.First().AuthorName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Questions.First().AnswerCount)
        </th>
        <th>
            Action
        </th>
    </tr>

    @foreach (var item in Model.Questions)
    {
        <tr class="@item.Question.Locked.ToString().ToLower()">
            <td>
                @Html.ActionLink(item.Question.Title, "Details", new { id = item.Question.Id })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AuthorName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AnswerCount)
            </td>
            <td class="action">
                @if (User.Identity.GetUserId() == item.Question.Author)
                {
                    if (!item.Question.Locked)
                    {
                        @Html.ActionLink("Close  ", "Close", new { id = item.Question.Id });
                    }
                    @Html.ActionLink("Delete  ", "Delete", new { id = item.Question.Id })
                }
                @if (User.IsInRole("admin"))
                {
                    if (item.Question.Locked)
                    {
                        @Html.ActionLink("Open  ", "Open", new { id = item.Question.Id });
                    }
                    @Html.ActionLink("Delete  ", "Delete", new { id = item.Question.Id })
                }
                @if (User.IsInRole("agent"))
                {
                    if (item.Question.Locked)
                    {
                        @Html.ActionLink("Open  ", "Open", new { id = item.Question.Id });
                    }
                }
                @if (User.Identity.IsAuthenticated)
                {
                    if (!item.Question.Locked)
                    {
                        @Html.ActionLink("Answer  ", "Create", "Answers", new { Id = item.Question.Id }, null);
                    }
                }
            </td>
        </tr>
    }
</table>