TechSupport/Controllers/AnswersController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TechSupport;

namespace TechSupport.Controllers
{
    public class AnswersController : Controller
    {
        private TechSupport20190613121821_dbEntities db = new TechSupport20190613121821_dbEntities();

        // GET: Answers
        public ActionResult Index()
        {
            var answers = db.Answers.Include(a => a.Answer1).Include(a => a.AspNetUser).Include(a => a.Question1);
            return View(answers.ToList());
        }

        // GET: Answers/Details/5
        public ActionResult Details(int? id, string sort)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = 
                db.Answers
                .Include(a => a.Answers1.Select(a1 => a1.AspNetUser))
                .SingleOrDefault(a => a.Id == id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            if (sort != null)
            {
                string sortOrder = (string)TempData["sortOrder"];
                if (sortOrder != null && sortOrder.Contains(sort) && sortOrder.Contains("desc"))
                {
                    sortOrder = sort + "_" + "asc";
                }
                else
                {
                    sortOrder = sort + "_" + "desc";
                }
                TempData["sortOrder"] = sortOrder;

            }

            return View(answer);
        }

        public Answer SortAnswers(Answer answer, string sortOrder)
        {
            switch (sortOrder)
            {
                case "time_asc":
                    answer.Answers1 = answer.Answers1.OrderBy(a => a.TimeCreated).ToList();
                    break;
                case "time_desc":
                    answer.Answers1 = answer.Answers1.OrderByDescending(a => a.TimeCreated).ToList();
                    break;
                case "likes_asc":
                    answer.Answers1 = answer.Answers1.OrderBy(a => a.Ratings.Where(r => r.Likes.Equals(true)).Count()).ToList();
                    break;
                case "likes_desc":
                    answer.Answers1 = answer.Answers1.OrderByDescending(a => a.Ratings.Where(r => r.Likes.Equals(true)).Count()).ToList();
                    break;
                case "dislikes_asc":
                    answer.Answers1 = answer.Answers1.OrderBy(a => a.Ratings.Where(r => r.Likes.Equals(false)).Count()).ToList();
                    break;
                case "dislikes_desc":
                    answer.Answers1 = answer.Answers1.OrderByDescending(a => a.Ratings.Where(r => r.Likes.Equals(false)).Count()).ToList();
                    break;
            }
            return answer;
        }

        // GET: Answers/Create
        public ActionResult Create(int? QuestionId, int? ReplyOn)
        {
            ViewBag.ReplyOn = new SelectList(db.Answers, "Id", "Author");
            ViewBag.Author = new SelectList(db.AspNetUsers, "Id", "Email");
            ViewBag.Question = new SelectList(db.Questions, "Id", "Title");
            TempData["QuestionToAnswer"] = QuestionId;
            TempData["AnswerToReply"] = ReplyOn;
            return View();
        }

        // POST: Answers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Text")] Answer answer)
        {
            int? QuestionId = (int?)TempData["QuestionToAnswer"];
            int? ReplyOn = (int?)TempData["AnswerToReply"];
            if (ModelState.IsValid)
            {
                answer.TimeCreated = DateTime.Now;
                answer.Question = QuestionId;
                answer.Author = User.Identity.GetUserId();
                answer.ReplyOn = ReplyOn;
                db.Answers.Add(answer);
                db.SaveChanges();
                return RedirectToAction("Index", "Questions");
            }

            ViewBag.ReplyOn = new SelectList(db.Answers, "Id", "Author", answer.ReplyOn);
            ViewBag.Author = new SelectList(db.AspNetUsers, "Id", "Email", answer.Author);
            ViewBag.Question = new SelectList(db.Questions, "Id", "Title", answer.Question);
            return View(answer);
        }

        // GET: Answers/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Answer answer = db.Answers.Find(id);
        //    if (answer == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.ReplyOn = new SelectList(db.Answers, "Id", "Author", answer.ReplyOn);
        //    ViewBag.Author = new SelectList(db.AspNetUsers, "Id", "Email", answer.Author);
        //    ViewBag.Question = new SelectList(db.Questions, "Id", "Title", answer.Question);
        //    return View(answer);
        //}

        //// POST: Answers/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,Question,ReplyOn,Author,TimeCreated,Text")] Answer answer)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(answer).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.ReplyOn = new SelectList(db.Answers, "Id", "Author", answer.ReplyOn);
        //    ViewBag.Author = new SelectList(db.AspNetUsers, "Id", "Email", answer.Author);
        //    ViewBag.Question = new SelectList(db.Questions, "Id", "Title", answer.Question);
        //    return View(answer);
        //}

        // GET: Answers/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Answer answer = db.Answers.Find(id);
        //    if (answer == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(answer);
        //}

        //// POST: Answers/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Answer answer = db.Answers.Include(a => a.Answers1).SingleOrDefault(a => a.Id.Equals(id));
        //    DeleteAnswer(answer);
        //    return RedirectToAction("Index");
        //}

        [Authorize(Roles = "admin")]
        public ActionResult Delete(int AnswerId, int QuestionId)
        {
            Answer answer = db.Answers.Include(a => a.Answers1).SingleOrDefault(a => a.Id.Equals(AnswerId));
            DeleteAnswer(answer);
            return Redirect("/Questions/Details/" + QuestionId);
        }

        [Authorize(Roles = "admin")]
        public ActionResult Delete(int AnswerId)
        {
            Answer answer = db.Answers.Include(a => a.Answers1).SingleOrDefault(a => a.Id.Equals(AnswerId));
            DeleteAnswer(answer);
            return Redirect("/Answers/Details/" + AnswerId);
        }

        public void DeleteAnswer(Answer answer)
        {
            if (answer.Answers1 != null)
            {
                foreach (var a in answer.Answers1.ToList())
                {
                    Answer ans = db.Answers.Include(an => an.Answers1).SingleOrDefault(an => an.Id.Equals(a.Id));
                    DeleteAnswer(ans);
                }
            } 
            db.Answers.Remove(answer);
            db.SaveChanges();            
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TechSupport/Controllers/RatingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TechSupport;

namespace TechSupport.Controllers
{
    public class RatingsController : Controller
    {
        private TechSupport20190613121821_dbEntities db = new TechSupport20190613121821_dbEntities();

        // GET: Ratings
        public ActionResult Index()
        {
            var ratings = db.Ratings.Include(r => r.Answer1).Include(r => r.AspNetUser1);
            return View(ratings.ToList());
        }

        // GET: Ratings/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rating rating = db.Ratings.Find(id);
            if (rating == null)
            {
                return HttpNotFound();
            }
            return View(rating);
        }

        // GET: Ratings/Create
        //public ActionResult Create()
        //{
        //    ViewBag.Answer = new SelectList(db.Answers, "Id", "Author");
        //    ViewBag.AspNetUser = new SelectList(db.AspNetUsers, "Id", "Email");
        //    return View();
        //}

        // POST: Ratings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "AspNetUser,Answer,Likes")] Rating rating)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Ratings.Add(rating);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.Answer = new SelectList(db.Answers, "Id", "Author", rating.Answer);
        //    ViewBag.AspNetUser = new SelectList(db.AspNetUsers, "Id", "Email", rating.AspNetUser);
        //    return View(rating);
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult CreateForQuestions(string UserId, int AnswerId, bool Likes, int QuestionId)
        {
            Rating Rating = db.Ratings.Find(UserId, AnswerId);
            if (Rating != null)
            {
                Rating.Likes = Likes;
                db.Entry(Rating).State = EntityState.Modified;
            }
            else
            {
                Rating = new Rating
                {
                    AspNetUser = UserId,
                    Answer = AnswerId,
                    Likes = Likes
                };
                db.Ratings.Add(Rating);
            }
            db.SaveChanges();
            return Redirect("/Questions/Details/" + QuestionId);
        }

        [Authorize]
        public ActionResult CreateForAnswer(string UserId, int AnswerId, bool Likes, int QuestionId)
        {
            Rating Rating = db.Ratings.Find(UserId, AnswerId);
            if (Rating != null)
            {
                Rating.Likes = Likes;
                db.Entry(Rating).State = EntityState.Modified;
            }
            else
            {
                Rating = new Rating
                {
                    AspNetUser = UserId,
                    Answer = AnswerId,
                    Likes = Likes
                };
                db.Ratings.Add(Rating);
            }
            db.SaveChanges();
            return Redirect("/Answers/Details/" + QuestionId);
        }

        // GET: Ratings/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rating rating = db.Ratings.Find(id);
            if (rating == null)
            {
                return HttpNotFound();
            }
            ViewBag.Answer = new SelectList(db.Answers, "Id", "Author", rating.Answer);
            ViewBag.AspNetUser = new SelectList(db.AspNetUsers, "Id", "Email", rating.AspNetUser);
            return View(rating);
        }

        // POST: Ratings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AspNetUser,Answer,Likes")] Rating rating)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rating).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Answer = new SelectList(db.Answers, "Id", "Author", rating.Answer);
            ViewBag.AspNetUser = new SelectList(db.AspNetUsers, "Id", "Email", rating.AspNetUser);
            return View(rating);
        }

        // GET: Ratings/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rating rating = db.Ratings.Find(id);
            if (rating == null)
            {
                return HttpNotFound();
            }
            return View(rating);
        }

        // POST: Ratings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Rating rating = db.Ratings.Find(id);
            db.Ratings.Remove(rating);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //public ActionResult Delete(int AnswerId, int QuestionId)
        //{
        //    Rating rating = db.Ratings.Find(AnswerId);
        //    db.Ratings.Remove(rating);
        //    db.SaveChanges();
        //    return Redirect("/Questions/Details/" + QuestionId);
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TechSupport/Views/Answers/Create.cshtml
@model TechSupport.Answer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Answer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TechSupport/Views/Answers/Delete.cshtml
@model TechSupport.Answer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Answer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TimeCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Answer1.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Answer1.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Question1.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Question1.Title)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TechSupport/Views/Answers/Details.cshtml
@using Microsoft.AspNet.Identity
@model TechSupport.Answer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Answer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TimeCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Answer1.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Answer1.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Question1.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Question1.Title)
        </dd>

    </dl>
</div>

<hr />

<h2>Answers</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        <th>
            @Html.ActionLink("TimeCreated", "Details", new { id = Model.Id, sort = "time" })
        </th>
        <th>
            @Html.ActionLink("Likes", "Details", new { id = Model.Id, sort = "likes" })
        </th>
        <th>
            @Html.ActionLink("Dislikes", "Details", new { id = Model.Id, sort = "dislikes" })
        </th>
    </tr>
    @foreach (var item in Model.Answers1)
    {
        <tr>
            <td>
                @Html.ActionLink(item.Text, "Details", "Answers", new { id = item.Id }, null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AspNetUser.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeCreated)
            </td>
            <td>
                @{
                    int likes = item.Ratings.Where(r => r.Likes.Equals(true)).Count();
                }
                @if (Request.IsAuthenticated)
                {
                    @Html.ActionLink("Like ", "CreateForAnswer", "Ratings", new { UserId = User.Identity.GetUserId(), AnswerId = item.Id, Likes = true, QuestionId = Model.Id }, null);
                }
                @Html.DisplayFor(modelItem => likes)
            </td>
            <td>
                @{
                    int dislikes = item.Ratings.Where(r => r.Likes.Equals(false)).Count();
                }
                @if (Request.IsAuthenticated)
                {
                    @Html.ActionLink("Dislike ", "CreateForAnswer", "Ratings", new { UserId = User.Identity.GetUserId(), AnswerId = item.Id, Likes = false, QuestionId = Model.Id }, null)
                }
                @Html.DisplayFor(modelItem => dislikes)
            </td>
            <td>
                @Html.ActionLink("Answer ", "Create", "Answers", new { ReplyOn = item.Id }, null)
                @if (User.IsInRole("admin"))
                {
                    @Html.ActionLink("Delete ", "Delete", "Answers", new { AnswerId = item.Id, QuestionId = Model.Id }, null)
                }
            </td>
        </tr>
    }
</table>

TechSupport/Views/Answers/Edit.cshtml
@model TechSupport.Answer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Answer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Question, "Question", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Question", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReplyOn, "ReplyOn", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ReplyOn", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ReplyOn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, "Author", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Author", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimeCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TechSupport/Views/Answers/Index.cshtml
@model IEnumerable<TechSupport.Answer>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TimeCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Question1.Title)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TimeCreated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AspNetUser.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Question1.Title)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>